### ISSUE TITLE
Setting launchctl-search-path has no effect

### ISSUE THREAD

**Issue by justmytwospence** [pekingduck/launchctl-el#2]
When I set `launchctl-search-path`:

```
(setq launchctl-search-path  '("~/.homesick/repos/local_dotfiles/home/Library/LaunchAgents"))
```

I still see a all the same launch agents, including the system ones.

**Comment by justmytwospence** [comment]
I was confused about the purpose of launch-ctl-search-path. Changing launchctl-filter-regex was what I wanted.

**Comment by pekingduck** [comment]
Glad you figured it out. Sorry about the lack of response...haven't been on github for quite a while...
